import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideRouter, withComponentInputBinding, withViewTransitions } from '@angular/router';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { providePrimeNG } from 'primeng/config';
import Aura from '@primeng/themes/aura';
import { MessageService, ConfirmationService } from 'primeng/api';
import {
  LucideAngularModule,
  // ── Icons ──
  Layers,
  Activity,
  CircleAlert,
  AlertTriangle,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  BarChart2,
  CircleCheck,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Download,
  LayoutDashboard,
  Plus,
  Settings,
  TrendingDown,
  TrendingUp,
  User,
  Users,
  UserPlus,
  Bell,
  BellOff,
  LogOut,
  Menu,
  Search,
  Check,
  Circle,
  Edit,
  Info,
  Trash2,
  Moon,
  Sun,
  CircleX,
  CircleHelp,
  CirclePlay,
  RotateCcw,
  RefreshCw,
  Archive,
  Award,
  Banknote,
  BookOpen,
  Brain,
  Briefcase,
  Bus,
  Building2,
  Calculator,
  Calendar,
  CalendarX,
  Camera,
  Car,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  ListChecks,
  Clock,
  CreditCard,
  DollarSign,
  Edit3,
  Eye,
  FileCheck,
  File,
  FilePen,
  FilePlus,
  FileSignature,
  FileText,
  Flag,
  FlaskConical,
  Printer,
  FolderOpen,
  GraduationCap,
  Image,
  Landmark,
  Loader,
  Mail,
  MessageCircle,
  Monitor,
  PenTool,
  Receipt,
  Send,
  Scroll,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Star,
  Stethoscope,
  Tag,
  Truck,
  Upload,
  UploadCloud,
  UserCheck,
  UserMinus,
  UserX,
  Video,
  Folder,
  Wrench,
  Ban,
  Home,
  ZoomIn,
  CalendarDays,
  CalendarClock,
  Save,
  Pencil,
  Gauge,
  X,
  Loader2,
  FileQuestion,
  FileBadge,
  FileCheck2,
  FileSpreadsheet,
  ExternalLink,
  FolderSearch,
  SearchX,
  MapPin,
  Phone,
  LifeBuoy,
  PlayCircle,
  HelpCircle,
  CalendarCheck,
  MonitorOff,
  CheckCheck,
  QrCode,
  Keyboard,
  Play,
  Square,
  History,
  // ── Matrícula pública ──
  Wallet,
  FileClock,
  LoaderCircle,
  // ── Gestión de Secretarias ──
  AtSign,
  IdCard,
  // ── Gestión de Relatores ──
  Mic,
} from 'lucide-angular';

import { routes } from './app.routes';
import { provideCoreAuth } from '@core/auth/provide-core-auth';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(
      routes,
      withComponentInputBinding(),
      withViewTransitions({
        onViewTransitionCreated: ({ transition, from, to }) => {
          const fromUrl = '/' + from.url.map((s) => s.path).join('/');
          const toUrl = '/' + to.url.map((s) => s.path).join('/');

          const isLoginToApp = fromUrl === '/login' && toUrl.startsWith('/app');
          const isAppToLogin = fromUrl.startsWith('/app') && toUrl === '/login';

          if (isLoginToApp) {
            document.documentElement.classList.add('vt-login-enter');
            transition.finished.then(() =>
              document.documentElement.classList.remove('vt-login-enter'),
            );
          } else if (isAppToLogin) {
            document.documentElement.classList.add('vt-login-leave');
            transition.finished.then(() =>
              document.documentElement.classList.remove('vt-login-leave'),
            );
          }
        },
      }),
    ),
    provideAnimationsAsync(),
    providePrimeNG({
      theme: {
        preset: Aura,
        options: {
          darkModeSelector: '.fake-dark-mode',
          cssLayer: {
            name: 'primeng',
            order: 'tailwind-base, primeng, tailwind-utilities',
          },
        },
      },
    }),
    provideCoreAuth(),
    MessageService,
    ConfirmationService,
    importProvidersFrom(
      LucideAngularModule.pick({
        Activity,
        CircleAlert,
        AlertTriangle,
        AlertCircle,
        ArrowLeft,
        ArrowRight,
        BarChart2,
        CircleCheck,
        CheckCircle,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        ChevronUp,
        Download,
        LayoutDashboard,
        Plus,
        Settings,
        TrendingDown,
        TrendingUp,
        User,
        Users,
        UserPlus,
        Bell,
        BellOff,
        LogOut,
        Menu,
        Search,
        Check,
        Circle,
        Edit,
        Info,
        Trash2,
        Moon,
        Sun,
        CircleX,
        CircleHelp,
        CirclePlay,
        RotateCcw,
        RefreshCw,
        Archive,
        Award,
        Banknote,
        BookOpen,
        Brain,
        Briefcase,
        Bus,
        Building2,
        Calculator,
        Calendar,
        CalendarX,
        Camera,
        Car,
        CheckSquare,
        ClipboardCheck,
        ClipboardList,
        ListChecks,
        Clock,
        CreditCard,
        DollarSign,
        Edit3,
        Eye,
        FileCheck,
        File,
        FilePen,
        FilePlus,
        FileSignature,
        FileSpreadsheet,
        FileText,
        Flag,
        FlaskConical,
        Printer,
        FolderOpen,
        GraduationCap,
        Image,
        Landmark,
        Loader,
        Mail,
        MessageCircle,
        Monitor,
        PenTool,
        Receipt,
        Send,
        Scroll,
        ShieldAlert,
        ShieldCheck,
        ShieldOff,
        Star,
        Stethoscope,
        Tag,
        Truck,
        Upload,
        UploadCloud,
        UserCheck,
        UserMinus,
        UserX,
        Video,
        Folder,
        FolderSearch,
        SearchX,
        Wrench,
        Ban,
        Home,
        Layers,
        ZoomIn,
        CalendarDays,
        CalendarClock,
        Save,
        Pencil,
        Gauge,
        X,
        Loader2,
        FileQuestion,
        FileBadge,
        FileCheck2,
        ExternalLink,
        LifeBuoy,
        PlayCircle,
        HelpCircle,
        CalendarCheck,
        MonitorOff,
        CheckCheck,
        QrCode,
        Keyboard,
        Play,
        Square,
        History,
        // Matrícula pública
        Wallet,
        FileClock,
        LoaderCircle,
        // ── Gestión de Secretarias ──
        AtSign,
        IdCard,
        MapPin,
        Phone,
        // ── Gestión de Relatores ──
        Mic,
      }),
    ),
  ],
};
