import { ApplicationConfig, LOCALE_ID, importProvidersFrom } from '@angular/core';
import { provideRouter, withComponentInputBinding, withViewTransitions } from '@angular/router';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { providePrimeNG } from 'primeng/config';
import Aura from '@primeng/themes/aura';
import { MessageService, ConfirmationService } from 'primeng/api';
import {
  LucideAngularModule,
  // ── Navigation & Layout ──
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUpDown,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ExternalLink,
  Home,
  LayoutDashboard,
  Layers,
  Menu,
  Globe,
  // ── Actions ──
  Check,
  CheckCheck,
  CheckCircle,
  CheckSquare,
  CircleCheck,
  CirclePlay,
  Download,
  Edit,
  Edit3,
  Eraser,
  Eye,
  Filter,
  Pencil,
  Play,
  Plus,
  Printer,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  SearchX,
  Send,
  Trash2,
  Upload,
  UploadCloud,
  X,
  XCircle,
  ZoomIn,
  // ── Status & Alerts ──
  AlertCircle,
  AlertTriangle,
  Ban,
  CircleAlert,
  CircleHelp,
  CircleX,
  Flag,
  HelpCircle,
  Info,
  MinusCircle,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  TriangleAlert,
  // ── User & People ──
  User,
  UserCheck,
  UserMinus,
  UserPen,
  UserPlus,
  UserX,
  Users,
  // ── Files & Documents ──
  ClipboardCheck,
  ClipboardList,
  File,
  FileBadge,
  FileCheck,
  FileCheck2,
  FileClock,
  FilePen,
  FilePlus,
  FileQuestion,
  FileSignature,
  FileSpreadsheet,
  FileText,
  FileX,
  FilterX,
  Folder,
  FolderOpen,
  FolderSearch,
  List,
  ListChecks,
  Scroll,
  // ── Calendar & Time ──
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarX,
  Clock,
  History,
  // ── Finance ──
  Banknote,
  Calculator,
  CreditCard,
  DollarSign,
  Landmark,
  Receipt,
  Tag,
  Wallet,
  // ── Communication ──
  AtSign,
  Bell,
  BellOff,
  Inbox,
  Mail,
  MessageCircle,
  MessageSquareOff,
  Mic,
  Phone,
  // ── Media & UI ──
  Camera,
  Image,
  Keyboard,
  Monitor,
  MonitorOff,
  Moon,
  PlayCircle,
  QrCode,
  Square,
  Sun,
  Video,
  // ── Business & Domain ──
  Activity,
  Archive,
  Award,
  BarChart2,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Bus,
  Car,
  FlaskConical,
  Gauge,
  GraduationCap,
  Hash,
  Coins,
  IdCard,
  LifeBuoy,
  Loader,
  Loader2,
  LoaderCircle,
  Lock,
  LogOut,
  MapPin,
  PenLine,
  PenTool,
  Settings,
  Settings2,
  Star,
  Stethoscope,
  Truck,
  Wrench,
  // ── Trending ──
  TrendingDown,
  TrendingUp,
  // ── Surfaces ──
  Circle,
  CalendarPlus,
  MousePointerClick,
  Unlock,
} from 'lucide-angular';

import { routes } from './app.routes';
import { provideCoreAuth } from '@core/auth/provide-core-auth';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(
      routes,
      withComponentInputBinding(),
      withViewTransitions({
        onViewTransitionCreated: ({ transition, from, to }) => {
          const fromUrl = '/' + from.url.map((s) => s.path).join('/');
          const toUrl = '/' + to.url.map((s) => s.path).join('/');

          const isLoginToApp = fromUrl === '/login' && toUrl.startsWith('/app');
          const isAppToLogin = fromUrl.startsWith('/app') && toUrl === '/login';

          if (isLoginToApp) {
            document.documentElement.classList.add('vt-login-enter');
            transition.finished.then(() =>
              document.documentElement.classList.remove('vt-login-enter'),
            );
          } else if (isAppToLogin) {
            document.documentElement.classList.add('vt-login-leave');
            transition.finished.then(() =>
              document.documentElement.classList.remove('vt-login-leave'),
            );
          }
        },
      }),
    ),
    provideAnimationsAsync(),
    providePrimeNG({
      theme: {
        preset: Aura,
        options: {
          darkModeSelector: '.fake-dark-mode',
          cssLayer: {
            name: 'primeng',
            order: 'tailwind-base, primeng, tailwind-utilities',
          },
        },
      },
    }),
    provideCoreAuth(),
    { provide: LOCALE_ID, useValue: 'es' },
    MessageService,
    ConfirmationService,
    importProvidersFrom(
      LucideAngularModule.pick({
        // ── Navigation & Layout ──
        ArrowLeft,
        ArrowRight,
        ArrowRightLeft,
        ArrowUpDown,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        ChevronUp,
        ExternalLink,
        Home,
        LayoutDashboard,
        Layers,
        Menu,
        Globe,
        // ── Actions ──
        Check,
        CheckCheck,
        CheckCircle,
        CheckSquare,
        CircleCheck,
        CirclePlay,
        Download,
        Edit,
        Edit3,
        Eraser,
        Eye,
        Filter,
        Pencil,
        Play,
        Plus,
        Printer,
        RefreshCw,
        RotateCcw,
        Save,
        Search,
        SearchX,
        Send,
        Trash2,
        Upload,
        UploadCloud,
        X,
        XCircle,
        ZoomIn,
        // ── Status & Alerts ──
        AlertCircle,
        AlertTriangle,
        Ban,
        CircleAlert,
        CircleHelp,
        CircleX,
        Flag,
        HelpCircle,
        Info,
        MinusCircle,
        Shield,
        ShieldAlert,
        ShieldCheck,
        ShieldOff,
        TriangleAlert,
        // ── User & People ──
        User,
        UserCheck,
        UserMinus,
        UserPen,
        UserPlus,
        UserX,
        Users,
        // ── Files & Documents ──
        ClipboardCheck,
        ClipboardList,
        File,
        FileBadge,
        FileCheck,
        FileCheck2,
        FileClock,
        FilePen,
        FilePlus,
        FileQuestion,
        FileSignature,
        FileSpreadsheet,
        FileText,
        FileX,
        FilterX,
        Folder,
        FolderOpen,
        FolderSearch,
        List,
        ListChecks,
        Scroll,
        // ── Calendar & Time ──
        Calendar,
        CalendarCheck,
        CalendarClock,
        CalendarDays,
        CalendarPlus,
        CalendarX,
        Clock,
        History,
        // ── Finance ──
        Banknote,
        Calculator,
        CreditCard,
        DollarSign,
        Landmark,
        Receipt,
        Tag,
        Wallet,
        // ── Communication ──
        AtSign,
        Bell,
        BellOff,
        Inbox,
        Mail,
        MessageCircle,
        MessageSquareOff,
        Mic,
        Phone,
        // ── Media & UI ──
        Camera,
        Image,
        Keyboard,
        Monitor,
        MonitorOff,
        Moon,
        PlayCircle,
        QrCode,
        Square,
        Sun,
        Video,
        // ── Business & Domain ──
        Activity,
        Archive,
        Award,
        BarChart2,
        BookOpen,
        Brain,
        Briefcase,
        Building2,
        Bus,
        Car,
        Circle,
        MousePointerClick,
        FlaskConical,
        Gauge,
        GraduationCap,
        Hash,
        Coins,
        IdCard,
        LifeBuoy,
        Loader,
        Loader2,
        LoaderCircle,
        Lock,
        LogOut,
        MapPin,
        PenLine,
        PenTool,
        Settings,
        Settings2,
        Star,
        Stethoscope,
        TrendingDown,
        TrendingUp,
        Truck,
        Unlock,
        Wrench,
      }),
    ),
  ],
};
