/**
 * EPQ Questions — Eysenck Personality Questionnaire (81 ítems Sí/No)
 * Compartido entre el formulario público (psych-test.component) y la
 * vista de evaluación administrativa (admin-pre-inscrito-drawer).
 */
export const EPQ_QUESTIONS: readonly string[] = [
  '¿Se detiene a pensar las cosas antes de hacerlas?',
  '¿Tiene Ud. a menudo altibajos de ánimo?',
  '¿Es Ud. una persona conversadora?',
  '¿Le preocupa tener deudas?',
  '¿Tiene Ud. algunas veces la impresión de sentirse mal sin razón?',
  '¿Cierra las puertas de su casa con llave cuidadosamente y asegura las ventanas todas las noches?',
  '¿Es Ud. más bien vivaz?',
  '¿Le afectaría mucho ver sufrir a un niño o a un animal?',
  '¿Se preocupa Ud. a menudo por cosas que no debería haber hecho o dicho?',
  '¿Puede Ud. habitualmente gozar a plenitud de una reunión social agradable?',
  '¿Es Ud. una persona irritable?',
  '¿Cree Ud. que los sistemas de seguros son una buena idea?',
  '¿Se siente Ud. fácilmente herido en sus sentimientos?',
  '¿Tiende a mantenerse en segundo plano en reuniones sociales?',
  '¿Tomaría Ud. drogas que pueden tener efectos desconocidos o peligrosos?',
  '¿Se siente Ud. a menudo hasta la coronilla?',
  '¿Ha tomado Ud. alguna vez algo (aunque sea un alfiler o un botón) que perteneciera a otra persona?',
  '¿Le gusta mucho salir de su casa?',
  '¿Goza Ud. hiriendo o martirizando a la gente que ama o quiere?',
  '¿Se siente a menudo perturbado por sentimientos de culpa?',
  '¿Tiene Ud. enemigos que quieren hacerle daño?',
  '¿Se considera una persona nerviosa?',
  '¿Tiene Ud. muchos amigos?',
  '¿Goza Ud. con las bromas que pueden a veces herir a otras personas?',
  '¿Es Ud. una persona que se hace problemas por todo?',
  '¿Significa mucho para Ud. la limpieza y los buenos modales?',
  '¿Se preocupa Ud. por cosas horribles que pudieran ocurrir?',
  '¿Es Ud. quien generalmente toma la iniciativa para hacer nuevos amigos?',
  '¿Se calificaría a sí mismo como una persona tensa o muy nerviosa?',
  '¿Permanece Ud. casi siempre callado cuando está con otras personas?',
  '¿Piensa Ud. que el matrimonio está pasado de moda y que debería abolirse?',
  '¿A veces se alaba un poco a sí mismo?',
  '¿Ud. puede animar con facilidad una fiesta aburrida?',
  '¿Le molesta la gente que maneja con cuidado?',
  '¿Se preocupa mucho por su salud sin haber motivos?',
  '¿Algunas veces ha dicho algo malo o desagradable acerca de otras personas?',
  '¿La mayoría de las cosas tienen para Ud. el mismo sabor?',
  '¿De niño, alguna vez fue Ud. atrevido con sus padres?',
  '¿Le gusta a Ud. mezclarse con la gente?',
  '¿Se preocupa Ud. si sabe que hay errores en su trabajo?',
  '¿Sufre Ud. de insomnio?',
  '¿Se lava Ud. siempre las manos antes de servirse las comidas?',
  '¿Tiene Ud. casi siempre una respuesta a mano cuando la gente le habla?',
  '¿Le gusta Ud. llegar con bastante anticipación a sus citas?',
  '¿Se siente Ud. a menudo desanimado y cansado sin motivo?',
  '¿Ha hecho alguna vez trampa en un juego?',
  '¿Le gusta hacer las cosas en las cuales tiene que actuar rápidamente?',
  '¿Es (o era) su madre una buena mujer?',
  '¿Siente a menudo que la vida es muy aburrida?',
  '¿Se ha aprovechado alguna vez de alguien?',
  '¿Hay personas que tratan de evitar su presencia?',
  '¿Le preocupa mucho su apariencia?',
  '¿Piensa Ud. que la gente gasta demasiado tiempo salvaguardando su futuro con ahorros y seguros?',
  '¿Ha deseado alguna vez estar muerto?',
  '¿Evitaría Ud. pagar sus impuestos si estuviera seguro de que nunca lo descubrirían?',
  '¿Es Ud. capaz de animar una fiesta?',
  '¿Trata Ud. de no ser descortés con la gente?',
  '¿Se preocupa por mucho tiempo después de una experiencia embarazosa?',
  '¿Cuando toma un tren es común que llegue a la estación a última hora?',
  '¿Sufre de los nervios?',
  '¿Alguna vez ha dicho Ud. algo a propósito para herir los sentimientos de alguien?',
  '¿Se rompen fácilmente sus amistades sin que Ud. tenga la culpa?',
  '¿Se siente solo a menudo?',
  '¿Siempre practica lo que predica?',
  '¿Le gusta a veces molestar a los animales?',
  '¿Se siente herido con facilidad cuando la gente encuentra un defecto en Ud. o en su trabajo?',
  '¿Le gusta estar en un ambiente en que haya bastante movimiento y excitación?',
  '¿Le gustaría que los demás le tuvieran miedo?',
  '¿Está Ud. algunas veces lleno de energía y otras lento y desanimado?',
  '¿Algunas veces deja para mañana lo que debería hacer hoy?',
  '¿Piensan otras personas que es Ud. muy activo y vivaz?',
  '¿Le cuenta la gente muchas mentiras?',
  '¿Es Ud. una persona muy sensible frente a ciertas cosas?',
  '¿Le daría mucha pena ver algún animal capturado en una trampa?',
  '¿Se considera Ud. una persona despierta, con "cachativa"?',
  '¿Le incomoda a Ud. ser el centro de atención en las reuniones sociales?',
  '¿Ha sentido alguna vez deseos de darse a sí mismo más de lo que le da a los demás en una repartición?',
  '¿Alguna vez se ha quedado con alguna cosa que no fuera suya?',
  '¿Le gusta que haya bastante movimiento y excitación alrededor suyo?',
  '¿Alguna vez ha engañado a una persona solo para lograr algo que Ud. quiere?',
  '¿Cree Ud. que otras personas lo encuentran muy activo y despierto?',
] as const;

export const EPQ_TOTAL = EPQ_QUESTIONS.length;
export const EPQ_PAGE_SIZE = 14;
export const EPQ_TOTAL_PAGES = Math.ceil(EPQ_TOTAL / EPQ_PAGE_SIZE);
